### ISSUE TITLE
custom Attribute Based Access Control | Angular & Rails

### ISSUE THREAD

**Issue by kaleemullah360** [datuxer/abac-explained#1]
I am implementing **Attribute Based Access Control** in angular typescript application with rails server.

I've searched for different solutions like followings but could not manage to implement cause of unclear solutions.

 1. [Custom Roles Based Access Control RBAC in ASP NET](https://www.codeproject.com/Articles/875547/Custom-Roles-Based-Access-Control-RBAC-in-ASP-NET)
 2. [simple attribute based access control with spring](https://dzone.com/articles/simple-attribute-based-access-control-with-spring)

The solution points to create a method for checking objects and its permissions list like this

    public boolean check(Object subject, Object resource, Object action, Object environment)

 1. Subject is the entity (mostly a user) that requests access
 2. Resource is the entity to be accessed (e.g. file, database record, Store Information, ...)
 3. Action is the operation to be carried on the resource (e.g. read, write, delete, ...)
 4. Environment is any information regarding the context of the access that might be used in making the access decision (e.g. time, network, ...).

please help guide me how can I implement custom access control system in efficient way without using `GEM` or `Package`.

looking for sample application, any suggestion and tips are welcome.

**Comment by devel-pa** [comment]
Sry, this are just my writings about dreams in my head and on my understanding.
I have no experience with Ruby, nor with Angular.
In ruby there are many already build things, like https://github.com/605data/strongbolt or https://github.com/SimplyBuilt/SimonSays and the reference one, old and unmaintained https://github.com/ryanb/cancan/
Probably on angular you'll be interested on this https://medium.com/@blacksonic86/angular-2-authentication-revisited-611bf7373bf9

**Comment by kaleemullah360** [comment]
thank you for your help. I already reached these topics. and in angular what ever technology we use. comes to hot module replacement. i.e remove a compiled module after app built and launch. I tried this in order to hide module from users but was in luck only for child routes.
finally what I understand is that hot module replacement is important for ABAC.
thank you.
